In [93]:
import numpy  as np

In [94]:
arr2 = np.arange(11)

In [95]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [96]:
arr2 >= 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [97]:
arr2[0:6]

array([0, 1, 2, 3, 4, 5])

In [98]:
slice_of_arr2 = arr2[0:6]

slice_of_arr2

array([0, 1, 2, 3, 4, 5])

In [99]:
slice_of_arr2[0:]=99

slice_of_arr2

array([99, 99, 99, 99, 99, 99])

In [101]:
slice_of_arr2=arr2[0:]

slice_of_arr2

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [102]:
# 배열의 복사
arr_copy = arr2.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [114]:
arr2_2d = [[5,10,15],[20,25,30],[35,40,45]]

In [128]:
np.array(arr2_2d)

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [131]:
np.array(arr2_2d)[1]

array([20, 25, 30])

In [132]:
arr2_2d

[[5, 10, 15], [20, 25, 30], [35, 40, 45]]

In [133]:
print("재미있는 데이터 분석")

재미있는 데이터 분석


In [163]:
np.array(arr2_2d)[0:1][0:2]

array([[ 5, 10, 15]])

In [221]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [212]:
np.array(arr2_2d)[0:2][0:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [240]:
np.array(arr_2d)[:2,1:3]

array([[10, 15],
       [25, 30]])

In [508]:
arr_2d = np.zeros((10,10))

In [509]:
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [520]:
arr_length = arr_2d.shape[1]

arr_length

10

In [521]:
for i in range(arr_length):
    arr_2d[i]=[i]

In [592]:
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [593]:
arr = np.arange(0,10)

In [594]:
arr[0:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [595]:
arr *2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [596]:
arr **2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [597]:
arr *0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [598]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [590]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [599]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [605]:
arr **3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [608]:
np.sqrt(arr)
# 제곱근을 나탄냈다.

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])